AUTO_SHIFT_ENABLE	= no
KEY_OVERRIDE_ENABLE	= yes
COMBO_ENABLE		= yes
TAP_DANCE_ENABLE	= no
DYNAMIC_TAPPING_TERM_ENABLE = yes

CAPS_WORD_ENABLE	= yes
SEND_STRING_ENABLE	= yes
UNICODE_ENABLE		= no

MOUSEKEY_ENABLE		= yes
EXTRAKEY_ENABLE		= yes

NKRO_ENABLE      	= yes
COMMAND_ENABLE   	= no
SWAP_HANDS_ENABLE 	= no
RGB_MATRIX_ENABLE 	= no

INTROSPECTION_KEYMAP_C = manna-harbour_miryoku.c
SRC += features/layer_lock.c
SRC += features/achordion.c
